#!/bin/bash
#### Check if the acmHostname is found, read it and compare to the current hostname
### If, they are the same, dont do anything
### If, the file is not found,this means 1st time run the PC,
###	add to it current hostname, create the home directory and set profile settings, and if there is a backup, restore it
### else, if it is found anad has a value different than the current,
###	delete the home directory for the old user,
###	And repeat the steps as the file is not found

################################ Script is written by:
############# Eng. Ahmed M. ElSayed
###############   ahmed.elsayed@acmacpc.org


function restoreData {
oldHostName=$1
curHostName=$2
if [ -d /backup/$oldHostName/cur ]
then
cp -r /backup/$oldHostName/cur/work/* /home/$curHostName/Desktop/work
chown -R $curHostName:$curHostName /home/$curHostName/Desktop/work
fi
}

function createUserProfile {
curHostName=`hostname`
mkdir -p /home/$curHostName/Desktop/work
######################## We have here to create the desktop shortcuts
mkdir -p /home/$curHostName/.config/autostart
cp /home/administrator/.config/autostart/set*.desktop /home/$curHostName/.config/autostart
chmod +x /home/$curHostName/.config/autostart/set*.desktop
chown -R $curHostName:$curHostName /home/$curHostName
chown -R $curHostName:$curHostName /home/$curHostName/.config
echo $curHostName > /etc/acmHostname
### Downloading all shortcuts
cd /home/$curHostName/Desktop
wget http://control/prog/common/CodeBlocks.desktop
wget http://control/prog/common/ECLipse.desktop
wget http://control/prog/common/Geany.desktop
wget http://control/prog/common/GEdit.desktop
wget http://control/prog/common/Net_Beans.desktop
wget http://control/prog/common/PC2_Team.desktop
wget http://control/prog/common/ScoreBoard.desktop
wget http://control/prog/common/STL_Documentation.desktop
sudo chown administrator *.desktop
chmod +rx *.desktop
}

function mountBackup {
teamName=$1
if [ ! -d /backup/$teamName ]
then 
 mkdir /backup/$teamName
fi
mount web:/backup/$teamName /backup/$teamName
}

function unmountBackup {
teamName=$1
umount  /backup/$teamName
rm -R /backup/$teamName
}


curHostName=`hostname`
if [ ! -f /etc/acmHostname ]
then
	createUserProfile
	mountBackup $curHostName
	/usr/sbin/backupwork &
	exit 0
fi
oldHostName=`cat /etc/acmHostname`
if [ $oldHostName != $curHostName ]
then
 rm -Rf /home/$oldHostName
 createUserProfile
 mountBackup $oldHostName
 restoreData $oldHostName $curHostName
 unmountBackup $oldHostName
 mountBackup $curHostName
else
 mountBackup $curHostName
fi
/usr/sbin/backupwork &

