#!/bin/bash
#### Check if the acpcHostname is found, read it and compare to the current hostname
### If, they are the same, dont do anything
### If, the file is not found,this means 1st time run the PC,
###	add to it current hostname, create the home directory and set profile settings, and if there is a backup, restore it
### else, if it is found anad has a value different than the current,
###	delete the home directory for the old user,
###	And repeat the steps as the file is not found

################################ Script is written by:
############# Eng. Ahmed M. ElSayed
###############   ahmed.elsayed@acpcacpc.org


function createUserProfile {
curHostName=`hostname`
### Get the team number, so create the user with the id that is team num + 3000,
#### so each local team account in each pc has a different uid to be suitable for permissions
###### in the web server
useradd -c "ACPC PC2  account" -u 4000 -m pc2
mkdir /home/$curHostName/Desktop

######################## We have here to create the desktop shortcuts
mkdir -p /home/$curHostName/.config/autostart
cp /home/administrator/.config/autostart/set*.desktop /home/$curHostName/.config/autostart
chmod +x /home/$curHostName/.config/autostart/set*.desktop
chown -R $curHostName:judges /home/$curHostName
chown -R $curHostName:judges /home/$curHostName/.config
echo $curHostName > /etc/acpcHostname
### Downloading all shortcuts
cd /home/$curHostName/Desktop
wget http://control/prog/common/ECLipse.desktop
wget http://control/prog/common/PC2_Team.desktop
wget http://control/prog/common/PC2_Admin.desktop
wget http://control/prog/common/PC2_Judge.desktop
wget http://control/prog/common/PC2_ScoreBoard.desktop
wget http://control/prog/common/PC2_Server.desktop
wget http://control/prog/common/BCompare.desktop
wget http://control/roles/pc2/Print
chmod +rx *.desktop
mkdir /home/$curHostName/html
chown -R $curHostName /home/$curHostName
}


curHostName=`hostname`


if [ ! -f /etc/acpcHostname ]
then
	createUserProfile
fi
oldHostName=`cat /etc/acpcHostname`
if [ $oldHostName != $curHostName ]
then
rm -Rf /home/$oldHostName
createUserProfile
fi

#### The next section, executes any commands only for the 1st time the pc start after install
if [ -f /1sttime ]
then
#151- Download firewalld direct rules, as permanent
wget http://control/roles/pc2/iptables.rules > /firewall.logs 2>&1
chmod +x iptables.rules >> /firewall.logs 2>&1
systemctl restart firewalld     >> /firewall.logs 2>&1
./iptables.rules        >> /firewall.logs 2>&1
rm iptables.rules       >> /firewall.logs 2>&1
rm /1sttime
rm /finalize
firewall-cmd --reload
fi

mount web:/var/www/scoreboard /home/pc2/html && chown pc2:pc2 /home/pc2/html

