#!/bin/sh 

# File:    loopprint
# Purpose: to create a local file connected to a remote printer
#          for use by the board
# Author:  pc2@ecs.csus.edu
# Revised: Sun May  1 18:17:17 PDT 2005
# 
# $Id: loopprint,v 1.1 2005/05/02 01:17:53 boudreat Exp $

# CUSTOMIZE HERE
# this is the local print queue
# test with: lp -d thisvalue file_to_print
PRINTER=balloon

# use this value in the balloon "Print Device(Port)"
# may need to change this to a user writable directory
FIFO=/tmp/balloonprinter

# the rest should not change

if [ -e $FIFO ]; then
	if [ ! -p $FIFO ]; then
		echo $FIFO is not a pipe, cannot continue
		exit 2
	fi
else
	# make the pipe
	mkfifo $FIFO
	# attempt to clean up after ourselves
	trap 'rm -f $FIFO;exit 0' 0
fi

while /bin/true
do

	cat $FIFO | lp -d $PRINTER

done
# eof

