#!/bin/bash
#### Check if the acpcHostname is found, read it and compare to the current hostname
### If, they are the same, dont do anything
### If, the file is not found,this means 1st time run the PC,
###	add to it current hostname, create the home directory and set profile settings, and if there is a backup, restore it
### else, if it is found anad has a value different than the current,
###	delete the home directory for the old user,
###	And repeat the steps as the file is not found

################################ Script is written by:
############# Eng. Ahmed M. ElSayed
###############   ahmed.elsayed@acpcacpc.org

function createUserProfile {
### Create the local account
curHostName=$(hostname)

### Get the team number, so create the user with the id that is team num + 2000, 
#### so each local team account in each pc has a different uid to be suitable for permissions
###### in the web server
ID=$(echo ${curHostName}|sed 's/team//g')
myUID=$[ ID + 2000]
useradd -c "ACPC Contestant account - ${curHostName}" -u ${myUID} -m ${curHostName}
echo ${curHostName} > /etc/acpcHostname
######################## We have here to create the desktop shortcuts
#mkdir -p /home/$curHostName/.config/autostart
#cp /home/administrator/.config/autostart/set*.desktop /home/$curHostName/.config/autostart
#chmod +x /home/$curHostName/.config/autostart/set*.desktop

## Download clion key
#cd /tmp
#wget http://control/prog/common/IDEs/clion.key

:<<COMMENTEOL
## Downloading all shortcuts
cd /home/$curHostName/Desktop/
wget http://control/prog/common/teams-desktop-entry/CodeBlocks.desktop
wget http://control/prog/common/teams-desktop-entry/ECLipse.desktop
wget http://control/prog/common/teams-desktop-entry/Geany.desktop
wget http://control/prog/common/teams-desktop-entry/GEdit.desktop
wget http://control/prog/common/teams-desktop-entry/PC2_Team.desktop
wget http://control/prog/common/teams-desktop-entry/ScoreBoard.desktop
wget http://control/prog/common/teams-desktop-entry/STL_Documentation.desktop
wget http://control/prog/common/teams-desktop-entry/Kill_Block.desktop
wget http://control/prog/common/teams-desktop-entry/intellij.desktop
wget http://control/prog/common/teams-desktop-entry/pycharm.desktop
wget http://control/prog/common/teams-desktop-entry/Clion.desktop
wget http://control/prog/common/teams-desktop-entry/Calculator.desktop 
wget http://control/prog/common/teams-desktop-entry/VisualStudioCode.desktop
#chmod a-x /home/$curHostName/Desktop/*
COMMENTEOL

cd /home/$curHostName/Desktop

sleep 10
DFS=$(sudo ls /home/$curHostName/Desktop/*.desktop)
for f in ${DFS}
do
        sudo -u $curHostName dbus-launch gio set "$f"  metadata::trusted true 
done
chmod a+x *.desktop
################################### change ownership 

}
dhclient
curHostName=`hostname`
if [ ! -f /etc/acpcHostname ]
then
	createUserProfile
	exit 0
fi
oldHostName=`cat /etc/acpcHostname`
if [ $oldHostName != $curHostName ]
then
# unmountSamples $oldHostName
 userdel ${oldHostName}
 rm -Rf /home/$oldHostName
 createUserProfile
fi

#### The next section, executes any commands only for the 1st time the pc start after install
#if [ -f /1sttime ]
#then
#151- Download firewalld direct rules, as permanent
#wget http://control/roles/contestant/iptables.rules > /firewall.logs 2>&1
#chmod +x iptables.rules >> /firewall.logs 2>&1
#systemctl restart firewalld     >> /firewall.logs 2>&1
#./iptables.rules        >> /firewall.logs 2>&1
#rm iptables.rules       >> /firewall.logs 2>&1
#rm /1sttime
#rm /finalize
#firewall-cmd --reload
#fi
