#!/bin/bash
#### Check if the acpcHostname is found, read it and compare to the current hostname
### If, they are the same, dont do anything
### If, the file is not found,this means 1st time run the PC,
###	add to it current hostname, create the home directory and set profile settings, and if there is a backup, restore it
### else, if it is found anad has a value different than the current,
###	delete the home directory for the old user,
###	And repeat the steps as the file is not found

################################ Script is written by:
############# Eng. Ahmed M. ElSayed
###############   ahmed.elsayed@acpcacpc.org


function createUserProfile {
curHostName=`hostname`
### Get the team number, so create the user with the id that is team num + 3000,
#### so each local team account in each pc has a different uid to be suitable for permissions
###### in the web server
ID=`echo $curHostName|sed 's/judge//g'`
myUID=`expr $ID + 3000`
useradd -c "ACPC Judge account - $curHostName" -u $myUID -g judges -m $curHostName

mkdir -p /home/$curHostName/Desktop/work
mkdir /home/$curHostName/Desktop/samples
mkdir /home/$curHostName/Desktop/JudgeCases
######################## We have here to create the desktop shortcuts
mkdir -p /home/$curHostName/.config/autostart
cp /home/administrator/.config/autostart/set*.desktop /home/$curHostName/.config/autostart
chmod +x /home/$curHostName/.config/autostart/set*.desktop
chown -R $curHostName:judges /home/$curHostName
chown -R $curHostName:judges /home/$curHostName/.config
echo $curHostName > /etc/acpcHostname
### Downloading all shortcuts
cd /home/$curHostName/Desktop
wget http://control/prog/common/CodeBlocks.desktop
wget http://control/prog/common/Clion.desktop
wget http://control/prog/common/ECLipse.desktop
wget http://control/prog/common/Geany.desktop
wget http://control/prog/common/GEdit.desktop
wget http://control/prog/common/PC2_Team.desktop
wget http://control/prog/common/PC2_Admin.desktop
wget http://control/prog/common/PC2_Judge.desktop
wget http://control/prog/common/ScoreBoard.desktop
wget http://control/prog/common/STL_Documentation.desktop
wget http://control/prog/common/Kill_Block.desktop
wget http://control/prog/common/intellij.desktop
wget http://control/prog/common/pycharm.desktop
wget http://control/prog/common/BCompare.desktop
chmod +rx *.desktop
cd /home/$curHostName
wget http://control/prog/common/IDEs/intellij/intelliconfig.tar
wget http://control/prog/common/IDEs/pycharm/pycharmconfig.tar
tar xf intelliconfig.tar
tar xf pycharmconfig.tar
rm pycharmconfig.tar intelliconfig.tar
chown -R $curHostName /home/$curHostName

}

function mountSamples {
judgeName=$1
#mount the directory as rw for judges
mount -o rw web:/home/samples /home/$judgeName/Desktop/samples
mount -o rw web:/home/JudgeCases /home/$judgeName/Desktop/JudgeCases
}

function unmountSamples {
judgeName=$1
umount /home/$judgeName/Desktop/samples
umount /home/$judgeName/Desktop/JudgeCases
}

curHostName=`hostname`
if [ ! -f /etc/acpcHostname ]
then
	createUserProfile
	mountSamples $curHostName
	exit 0
fi
oldHostName=`cat /etc/acpcHostname`
if [ $oldHostName != $curHostName ]
then
unmountSamples $oldHostName
rm -Rf /home/$oldHostName
createUserProfile
fi
#### The next section, executes any commands only for the 1st time the pc start after install
if [ -f /1sttime ]
then
#151- Download firewalld direct rules, as permanent
wget http://control/roles/judge/iptables.rules > /firewall.logs 2>&1
chmod +x iptables.rules >> /firewall.logs 2>&1
systemctl restart firewalld     >> /firewall.logs 2>&1
./iptables.rules        >> /firewall.logs 2>&1
rm iptables.rules       >> /firewall.logs 2>&1
rm /1sttime
rm /finalize
firewall-cmd --reload
fi

mountSamples $curHostName

