#!/bin/sh

### BEGIN INIT INFO
# Provides:          finalize
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop apache2 web server
### END INIT INFO

######################################### Finalize script
# Is used to perform any additional tasks Just after the machine rebooted after
#   installation
########################################

cd /tmp

### 10- Download the server public key

wget http://control/prog/common/authorized_keys
mkdir /root/.ssh
sudo cp authorized_keys /root/.ssh
sudo rm authorized_keys

### 30- update the mirror list

 apt-get update

### 40- Install gnome-panel to deal with shortcuts
	##Disable gnome-initial-setuo
 	apt-get -y purge gnome-initial-setup 
 	#apt-get -y install autofs debconf-utils firewalld wine dvipsk-ja texlive-binaries texlive-latex-base
 	apt-get -y install autofs debconf-utils firewalld  wine-stable texlive-latex-base texlive-binaries
 	apt-get -y --force-yes install --no-install-recommends gnome-panel


### 50-Install 3rd party IDEs
#Netbeans removed in 2019 version
#	wget http://control//prog/common/IDEs/netbeans/netbeans-8.2-cpp-linux-x86.sh
#	wget http://control//prog/common/IDEs/netbeans/netbeans-8.2-javase-linux.sh
	wget http://control//prog/common/IDEs/clion/CLion-2018.1.5.tar.gz
#New IDEs version according to icpc
        wget http://control//prog/common/IDEs/eclipse/eclipse-cpp-photon-R-linux-gtk.tar.gz
        wget http://control//prog/common/IDEs/eclipse/eclipse-java-photon-R-linux-gtk.tar.gz
        wget http://control//prog/common/IDEs/intellij/ideaIC-2018.1.4.tar.gz
        wget http://control//prog/common/IDEs/pycharm/pycharm-community-2018.1.4.tar.gz
        wget http://control//prog/common/IDEs/clion/CLion-2018.1.5.tar.gz
        tar zxf CLion-2018.1.5.tar.gz
        tar zxf eclipse-cpp-photon-R-linux-gtk.tar.gz
        tar zxf eclipse-java-photon-R-linux-gtk.tar.gz
        tar zxf ideaIC-2018.1.4.tar.gz
        tar zxf pycharm-community-2018.1.4.tar.gz
        mv eclipse /usr/local
        mv idea-IC-181.5087.20 /usr/local/idea-IC
        mv pycharm-community-2018.1.4 /usr/local/pycharm
        mv clion-2018.1.5 /usr/local/clion
#       sh /usr/local/clion/bin/clion.sh --silent
        rm CLion-2018.1.5.tar.gz
#Netbeans removed in 2019 version
#	sh netbeans-8.2-javase-linux.sh --silent
#        sh netbeans-8.2-cpp-linux-x86.sh --silent
#        rm netbeans-8.2-javase-linux.sh
#        rm netbeans-8.2-cpp-linux-x86.sh

### 70- Downloading cups configuration files
 wget http://control/prog/common/cupsd.conf
 mv cupsd.conf /etc/cups

###75- Disable what is new and welcome screen
 wget http://control/adm/roles/judge/custom.conf
 mv custom.conf /etc/gdm3/custom.conf

### 90- Downloading PC2, and extract it
 wget http://control/prog/common/pc2.tar.gz
 tar zxf pc2.tar.gz
 REL=`ls -ld pc2-* | awk ' { print $9 } ' | cut -d'-' -f 2`
 mv pc2-$REL /usr/local/
 ln -s  /usr/local/pc2-$REL /usr/local/pc2
 chmod +x /usr/local/pc2/bin/pc2*
 cat /usr/local/pc2/pc2v9.ini | sed 's/localhost/pc2/g' > /tmp/pc2v9.ini
 cp /tmp/pc2v9.ini /usr/local/pc2/pc2v9.ini
 rm /tmp/pc2v9.ini

### 100- Downloading gnome-settings-daemon.desktop to set the background img
 wget http://control/roles/judge/setbg.desktop
 wget http://control/roles/judge/setspan.desktop
 mkdir -p /home/administrator/.config/autostart
 cp set*.desktop /home/administrator/.config/autostart
 rm set*.desktop
 chmod +x /home/administrator/.config/autostart/set*.desktop
 #wget http://control/prog/common/bg.jpg
 #cp bg.jpg /etc/bg.jpg
 #rm bg.jpg
 #####Change Login Screen Background
 #wget http://control/prog/common/loginbg.jpg
 #cp loginbg.jpg /etc/loginbg.jpg
 #cp /etc/loginbg.jpg /usr/share/backgrounds/warty-final-ubuntu.png
 #rm loginbg.jpg
 chown -R administrator /home/administrator/*
 chown -R administrator /home/administrator/.config


### 130- Get the configProfile, and addit to the startup
 wget http://control/roles/judge/configProfile
 cp configProfile /etc/systemd/system
 chmod +x /etc/systemd/system/configProfile
 wget http://control/roles/judge/configProfile.service
 mv configProfile.service /lib/systemd/system
 systemctl enable configProfile.service
 rm configProfile


### 140 - Setting up environment variables
echo "SHELL=/bin/bash">>/etc/environment
echo "export SHELL">>/etc/environment

### 141- Download bcompare and install it
 wget http://control/prog/common/bcompare-4.2.5.23088_i386.deb
 dpkg -i bcompare-4.2.5.23088_i386.deb
 apt -y -f install
 rm bcompare-4.2.5.23088_i386.deb

### 150 - Get the doTask, getProcess, and dos2unix scripts for External Validator
 wget http://control/roles/judge/getProcess
 wget http://control/roles/judge/doTask
 wget http://control/roles/judge/dos2unix
 cp getProcess doTask dos2unix /usr/sbin
 rm getProcess doTask dos2unix
 chmod +x /usr/sbin/getProcess /usr/sbin/doTask /usr/sbin/dos2unix

 ### 155 - Setting up umask for Judges Profile to give their created files read/write access over samples and JudgesCases
 echo "umask=002">>/etc/profile

## 160- Disable NTP
timedatectl set-ntp off

### 161- Disable online upgrade check
rm /etc/update-motd.d/91-release-upgrade

### 162: Create the judges group
groupadd -g 3000 judges

######190- configure 1st time start
touch /1sttime

rm finalize

exit 0
